// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://waomzqanlsposlfbcfco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indhb216cWFubHNwb3NsZmJjZmNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODUwNDAsImV4cCI6MjA3MzM2MTA0MH0.YkyJeq5Vl9zp9K8-EPmcTrVeIoGmHXoclDQ993N6vb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});